// Este arquivo contém apenas os dados do jogo.
// Estrutura: { n: "Palavra Inocente", i: "Palavra Impostor" }

const database = {
    movies: [
        { n: "Harry Potter", i: "Percy Jackson" },
        { n: "Vingadores", i: "Liga da Justiça" },
        { n: "Homem-Aranha", i: "Batman" },
        { n: "Capitão América", i: "Homem de Ferro" },
        { n: "Pantera Negra", i: "Shazam" },
        { n: "Toy Story", i: "Os Incríveis" },
        { n: "Procurando Nemo", i: "A Era do Gelo" },
        { n: "Shrek", i: "Madagascar" },
        { n: "Meu Malvado Favorito", i: "Minions" },
        { n: "Jurassic Park", i: "King Kong" },
        { n: "Transformers", i: "Power Rangers" },
        { n: "Star Wars", i: "Star Trek" },
        { n: "Matrix", i: "O Exterminador do Futuro" },
        { n: "Piratas do Caribe", i: "A Múmia" },
        { n: "O Rei Leão", i: "Tarzan" },
        { n: "Frozen", i: "Moana" },
        { n: "Carros", i: "Turbo" },
        { n: "Velozes e Furiosos", i: "Need for Speed" },
        { n: "Divertida Mente", i: "Viva – A Vida é uma Festa" },
        { n: "Avatar", i: "Titanic" },
        { n: "Rocky", i: "Creed" },
        { n: "Rambo", i: "Mad Max" },
        { n: "Esqueceram de Mim", i: "Diário de um Banana" },
        { n: "O Máskara", i: "Ace Ventura" },
        { n: "V de Vingança", i: "Watchmen" },
        { n: "It: A Coisa", i: "Annabelle" },
        { n: "A Freira", i: "Invocação do Mal" },
        { n: "O Chamado", i: "A Morte do Demônio" },
        { n: "O Iluminado", i: "Psicose" },
        { n: "O Lado Bom da Vida", i: "A Culpa é das Estrelas" },
        { n: "Quem Quer Ser um Milionário?", i: "À Procura da Felicidade" },
        { n: "Forrest Gump", i: "O Curioso Caso de Benjamin Button" },
        { n: "Legalmente Loira", i: "As Branquelas" },
        { n: "As Branquelas", i: "Todo Mundo em Pânico" },
        { n: "Gente Grande", i: "Se Beber Não Case" },
        { n: "Click", i: "O Paizão" },
        { n: "O Paizão", i: "Esposa de Mentirinha" },
        { n: "Uma Noite no Museu", i: "Jumanji" },
        { n: "Jumanji", i: "Zathura" },
        { n: "A Procura da Felicidade", i: "Um Sonho de Liberdade" },
        { n: "O Lobo de Wall Street", i: "A Grande Aposta" },
        { n: "O Terminal", i: "Náufrago" },
        { n: "O Náufrago", i: "Capitão Phillips" },
        { n: "O Grande Gatsby", i: "O Amor é Cego" },
        { n: "Uma Linda Mulher", i: "Pretty Little Liars" },
        { n: "De Repente 30", i: "Sexta-Feira Muito Louca" },
        { n: "Se Beber Não Case", i: "As Branquelas" },
        { n: "MIB – Homens de Preto", i: "Ghostbusters" },
        { n: "Karate Kid", i: "Cobra Kai" },
        { n: "A Lagoa Azul", i: "Romeu + Julieta" },
        { n: "Harry Potter e a Pedra Filosofal", i: "Percy Jackson: O Ladrão de Raios" },
        { n: "Titanic", i: "Avatar" },
        { n: "Vingadores", i: "Liga da Justiça" },
        { n: "Homem-Aranha", i: "The Flash" },
        { n: "Capitão América", i: "Thor" },
        { n: "Homem de Ferro", i: "Doutor Estranho" },
        { n: "Pantera Negra", i: "Aquaman" },
        { n: "Batman: O Cavaleiro das Trevas", i: "Coringa" },
        { n: "O Rei Leão", i: "Tarzan" },
        { n: "Toy Story", i: "Monstros S.A." },
        { n: "Procurando Nemo", i: "A Era do Gelo" },
        { n: "Os Incríveis", i: "Big Hero 6" },
        { n: "Shrek", i: "Madagascar" },
        { n: "Meu Malvado Favorito", i: "Os Minions" },
        { n: "Frozen", i: "Moana" },
        { n: "Carros", i: "Turbo" },
        { n: "Velozes e Furiosos", i: "Transformers" },
        { n: "Matrix", i: "O Exterminador do Futuro 2" },
        { n: "Star Wars", i: "Star Trek" },
        { n: "Jurassic Park", i: "King Kong" },
        { n: "Avatar", i: "John Carter" },
        { n: "O Lobo de Wall Street", i: "A Grande Aposta" },
        { n: "O Irlandês", i: "Cassino" },
        { n: "Clube da Luta", i: "Cisne Negro" },
        { n: "Pulp Fiction", i: "Cães de Aluguel" },
        { n: "Forrest Gump", i: "O Curioso Caso de Benjamin Button" },
        { n: "A Origem", i: "Interestelar" },
        { n: "Interstellar", i: "Gravidade" },
        { n: "O Pianista", i: "A Lista de Schindler" },
        { n: "O Resgate do Soldado Ryan", i: "1917" },
        { n: "Rocky", i: "Creed" },
        { n: "Rambo", i: "Duro de Matar" },
        { n: "Se Beber Não Case", i: "Gente Grande" },
        { n: "Click", i: "Um Faz de Conta que Acontece" },
        { n: "As Branquelas", i: "Todo Mundo em Pânico" },
        { n: "American Pie", i: "Superbad" },
        { n: "Jumanji", i: "Zathura" },
        { n: "Uma Noite no Museu", i: "Jumanji (2017)" },
        { n: "O Máskara", i: "Ace Ventura" },
        { n: "Karate Kid", i: "Kung Fu Panda" },
        { n: "O Auto da Compadecida", i: "Minha Mãe é uma Peça" },
        { n: "Tropa de Elite", i: "Cidade de Deus" },
        { n: "Central do Brasil", i: "Que Horas Ela Volta?" },
        { n: "Minha Mãe é Uma Peça", i: "Se Eu Fosse Você" },
        { n: "Carandiru", i: "Bicho de Sete Cabeças" },
        { n: "Bacurau", i: "O Som ao Redor" },
        { n: "Mogli", i: "Rei Leão Live Action" },
        { n: "Up — Altas Aventuras", i: "Wall-E" },
        { n: "Divertida Mente", i: "Soul" },
        { n: "Os Caça-Fantasmas", i: "MIB: Homens de Preto" },
        { n: "Caça-Fantasmas", i: "Gremlins" },
        { n: "It: A Coisa", i: "Annabelle" },
        { n: "Invocação do Mal", i: "A Freira" },
        { n: "O Chamado", i: "O Grito" },
        { n: "O Iluminado", i: "Psicose" },
        { n: "O Exorcista", i: "Hereditário" },
        { n: "O Terminal", i: "O Náufrago" },
        { n: "Náufrago", i: "O Impossível" },
        { n: "Crepúsculo", i: "Diário de um Vampiro" },
        { n: "Jogos Vorazes", i: "Divergente" },
        { n: "Maze Runner", i: "A 5ª Onda" },
        { n: "O Diabo Veste Prada", i: "Cruella" },
        { n: "Barbie", i: "Legalmente Loira" },
        { n: "High School Musical", i: "Camp Rock" },
        { n: "Glee", i: "Sing" },
        { n: "Os Penetras", i: "Até que a Sorte nos Separe" },
        { n: "A Lagoa Azul", i: "Querido John" },
        { n: "A Proposta", i: "Como Perder um Homem em 10 Dias" },
        { n: "Como Se Fosse a Primeira Vez", i: "Click" },
        { n: "Um Amor para Recordar", i: "A Culpa é das Estrelas" },
        { n: "Marley & Eu", i: "Quatro Vidas de um Cachorro" },
        { n: "À Procura da Felicidade", i: "Um Sonho de Liberdade" },
        { n: "Os Vingadores", i: "Liga da Justiça" },
        { n: "Cinderela", i: "A Bela e a Fera" },
        { n: "A Bela e a Fera", i: "Aladdin" },
        { n: "Aladdin", i: "O Rei Leão" },
        { n: "Ratattouille", i: "Os Incríveis" },
        { n: "Moana", i: "Frozen" },
        { n: "Planeta dos Macacos", i: "Interestelar" },
        { n: "O Dia Depois de Amanhã", i: "2012" },
        { n: "Armageddon", i: "Impacto Profundo" },
        { n: "Homens de Preto", i: "Caça-Fantasmas" },
        { n: "King Kong", i: "Godzilla" },
        { n: "Godzilla vs Kong", i: "Pacific Rim" },
        { n: "Meu Primeiro Amor", i: "Extraordinário" },
        { n: "O Grande Gatsby", i: "Orgulho e Preconceito" },
        { n: "O Rei do Show", i: "La La Land" },
        { n: "Madagascar", i: "A Era do Gelo" },
        { n: "Zootopia", i: "Sing" },
        { n: "Detona Ralph", i: "Moana" },
        { n: "Sonic", i: "Detective Pikachu" },
        { n: "O Homem Invisível", i: "Bird Box" },
        { n: "Her", i: "Ex Machina" },
        { n: "À Espreita do Mal", i: "A Morte Te Dá Parabéns" },
        { n: "Turbo", i: "Carros 2" },
        { n: "O Protetor", i: "John Wick" },
        { n: "John Wick", i: "Atômica" },
        { n: "Shrek", i: "Madagascar" },
        { n: "A Era do Gelo", i: "Procurando Nemo" },
        { n: "Toy Story", i: "Monstros S.A." },
        { n: "Carros", i: "Turbo" },
        { n: "Os Incríveis", i: "Big Hero 6" },
        { n: "Homem-Aranha", i: "Batman" },
        { n: "Vingadores", i: "Liga da Justiça" },
        { n: "Harry Potter", i: "Percy Jackson" },
        { n: "Jurassic Park", i: "King Kong" },
        { n: "Transformers", i: "Pacific Rim" },
        { n: "Velozes e Furiosos", i: "Need for Speed" },
        { n: "Piratas do Caribe", i: "A Múmia" },
        { n: "Karate Kid", i: "Rocky" },
        { n: "Jumanji", i: "Zathura" },
        { n: "Meninas Malvadas", i: "As Branquelas" },
        { n: "Todo Mundo em Pânico", i: "Scary Movie 5" },
        { n: "Se Beber Não Case", i: "Gente Grande" },
        { n: "Madagascar", i: "Kung Fu Panda" },
        { n: "Zootopia", i: "Sing" },
        { n: "Sonic", i: "Detective Pikachu" },
        { n: "O Máskara", i: "Ace Ventura" },
        { n: "Titanic", i: "Diário de uma Paixão" },
        { n: "Avatar", i: "Alita" },
        { n: "Matrix", i: "O Exterminador do Futuro" },
        { n: "O Rei Leão", i: "Tarzan" },
        { n: "O Auto da Compadecida", i: "Minha Mãe é uma Peça" },
        { n: "Tropa de Elite", i: "Cidade de Deus" },
        { n: "Cidade de Deus", i: "Carandiru" },
        { n: "Minha Mãe é Uma Peça", i: "Até que a Sorte nos Separe" },
        { n: "Central do Brasil", i: "Que Horas Ela Volta?" },
        { n: "Dois Filhos de Francisco", i: "Gonzaga: De Pai para Filho" },
        { n: "Os Farofeiros", i: "Sai de Baixo" },
        { n: "Se Eu Fosse Você", i: "Dona Flor e Seus Dois Maridos" },
        { n: "De Pernas pro Ar", i: "Meu Passado Me Condena" },
        { n: "Minha Vida em Marte", i: "Os Homens São de Marte" },
        { n: "Até que a Sorte nos Separe", i: "Os Farofeiros" },
        { n: "Carandiru", i: "Pixote" },
        { n: "Bacurau", i: "O Som ao Redor" },
        { n: "Que Horas Ela Volta?", i: "Central do Brasil" },
        { n: "O Palhaço", i: "Cheiro do Ralo" },
        { n: "Lisbela e o Prisioneiro", i: "O Homem que Desafiou o Diabo" },
        { n: "Domésticas", i: "Os Normais" },
        { n: "Tudo Bem no Natal que Vem", i: "Um Natal Muito Louco" },
        { n: "A Grande Família", i: "Sai de Baixo" },
        { n: "Ó Paí, Ó", i: "Dona Flor e Seus Dois Maridos" },
        { n: "Meu Nome Não É Johnny", i: "Tropa de Elite" },
        { n: "Flores Raras", i: "Olga" },
        { n: "O Homem do Futuro", i: "Xuxa e os Duendes" },
        { n: "Xuxa e os Duendes", i: "Lua de Cristal" },
        { n: "O Menino Maluquinho", i: "Castelo Rá-Tim-Bum" },
        { n: "Homem de Ferro", i: "Capitão América" },
        { n: "Thor", i: "Shazam" },
        { n: "Pantera Negra", i: "Aquaman" },
        { n: "Batman Begins", i: "O Homem de Aço" },
        { n: "Capitã Marvel", i: "Mulher-Maravilha" },
        { n: "Guardians of the Galaxy", i: "Star Wars" },
        { n: "Como Eu Era Antes de Você", i: "A Culpa é das Estrelas" },
        { n: "Diário de uma Paixão", i: "Amor para Recordar" },
        { n: "Nasce uma Estrela", i: "La La Land" },
        { n: "Extraordinário", i: "Milagre na Cela 7" },
        { n: "O Quarto de Jack", i: "O Quarto do Pânico" },
        { n: "Frozen", i: "Moana" },
        { n: "Encanto", i: "Viva: A Vida é uma Festa" },
        { n: "Ratatouille", i: "Os Incríveis" },
        { n: "Viva – A Vida é uma Festa", i: "Up" },
        { n: "Monstros S.A.", i: "Universidade Monstros" },
        { n: "Madagascar", i: "Rio" },
        { n: "Rio", i: "Happy Feet" },
        { n: "Pets", i: "Bolt" },
        { n: "Kung Fu Panda", i: "Como Treinar Seu Dragão" },
        { n: "Divertida Mente", i: "Soul" },
        { n: "Procurando Nemo", i: "Procurando Dory" },
        { n: "A Era do Gelo", i: "Os Croods" },
        { n: "Os Croods", i: "Hotel Transilvânia" },
        { n: "Hotel Transilvânia", i: "Shrek" },
        { n: "Tarzan", i: "O Rei Leão" },
        { n: "Pequena Sereia", i: "Pocahontas" },
        { n: "Aladdin", i: "A Bela e a Fera" },
        { n: "A Bela e a Fera", i: "A Dama e o Vagabundo" },
        { n: "Cinderela", i: "Branca de Neve" },
        { n: "Branca de Neve", i: "A Bela Adormecida" },
        { n: "Toy Story 3", i: "Toy Story 2" },
        { n: "Os Minions", i: "Meu Malvado Favorito" },
        { n: "Sério… TODOS já viram", i: "Frozen" },
        { n: "WALL-E", i: "Robôs" },
        { n: "Detona Ralph", i: "WiFi Ralph" }
    ],

    games: [
        { n: "God of War", i: "Shadow of the Colossus" },
        { n: "Red Dead Redemption 2", i: "The Witcher 2" },
        { n: "FIFA", i: "Wii Sports" },
        { n: "Halo", i: "Warframe" },
        { n: "Terraria", i: "Starbound" },
        { n: "Cuphead", i: "Ori and the Will of the Wisps" },
        { n: "Dead by Daylight", i: "Phasmophobia" },
        { n: "Overwatch", i: "Paladins" },
        { n: "Metal Gear", i: "Control" },
        { n: "Forza Horizon", i: "Trackmania" },
        { n: "Clash Royale", i: "Brawl Stars" },
        { n: "Brawl Stars", i: "Fall Guys" },
        { n: "Candy Crush", i: "Bejeweled" },
        { n: "Just Dance", i: "Beat Saber" },
        { n: "Mortal Kombat", i: "Killer Instinct" },
        { n: "Assassin’s Creed", i: "Dark Souls" },
        { n: "Far Cry", i: "Metal Gear Survive" },
        { n: "Hitman", i: "Watch Dogs" },
        { n: "Horizon Zero Dawn", i: "Enslaved: Odyssey to the West" },
        { n: "The Witcher 3", i: "Dragon Age: Inquisition" },
        { n: "Subnautica", i: "The Long Dark" },
        { n: "Limbo", i: "Inside (versão alternativa)" },
        { n: "FIFA Street", i: "Tony Hawk’s Pro Skater" },
        { n: "Mario Party", i: "Overcooked" },
        { n: "Kirby", i: "Rayman" },
        { n: "Portal", i: "The Talos Principle" },
        { n: "Metal Slug", i: "Broforce" },
        { n: "Left 4 Dead", i: "GTFO" },
        { n: "Warframe", i: "Anthem" },
        { n: "Team Fortress 2", i: "Plants vs Zombies: Garden Warfare" },
        { n: "Final Fantasy", i: "Octopath Traveler" },
        { n: "The Last of Us", i: "Telltale’s The Walking Dead" },
        { n: "Fortnite", i: "Splatoon" },
        { n: "Among Us", i: "Town of Salem" },
        { n: "Super Mario Bros", i: "Celeste" },
        { n: "The Legend of Zelda", i: "Shadow of Mordor" },
        { n: "Counter-Strike", i: "Escape from Tarkov" },
        { n: "Pokémon", i: "Yo-kai Watch" },
        { n: "Call of Duty", i: "Spec Ops: The Line" },
        { n: "The Sims", i: "House Flipper" },
        { n: "Baldur’s Gate", i: "Pillars of Eternity" },
        { n: "Dota 2", i: "Heroes of the Storm" },
        { n: "Resident Evil", i: "The Evil Within" },
        { n: "Mario Kart", i: "Garfield Kart" },
        { n: "Monopoly", i: "Catan" },
        { n: "Uno", i: "Skip-Bo" },
        { n: "Poker", i: "Blackjack" },
        { n: "Apex Legends", i: "TITANFALL 2" },
        { n: "Paladins", i: "Rogue Company" },
        { n: "Ark: Survival Evolved", i: "The Isle" },
        { n: "Sea of Thieves", i: "Raft" },
        { n: "Grounded", i: "Terraria 3D" },
        { n: "The Forest", i: "The Long Dark" },
        { n: "Escape from Tarkov", i: "Insurgency Sandstorm" },
        { n: "Dead Island", i: "State of Decay" },
        { n: "Plants vs Zombies", i: "Kingdom Rush" },
        { n: "Geometry Dash", i: "Thumper" },
        { n: "Donkey Kong", i: "Klonoa" },
        { n: "Gran Turismo", i: "Grid" },
        { n: "Spyro", i: "A Hat in Time" },
        { n: "Splatoon", i: "ARMS" },
        { n: "Metroid", i: "Prey" },
        { n: "Pikmin", i: "Overlord" },
        { n: "Fire Emblem", i: "Total War: Three Kingdoms" },
        { n: "Xenoblade Chronicles", i: "Ni No Kuni" },
        { n: "Path of Exile", i: "Grim Dawn" },
        { n: "MapleStory", i: "Elsword" },
        { n: "RuneScape", i: "Albion Online" },
        { n: "Hades", i: "Transistor" },
        { n: "Stardew Valley", i: "My Time at Portia" },
        { n: "RimWorld", i: "Oxygen Not Included" },
        { n: "Civilization VI", i: "Crusader Kings III" },
        { n: "Stellaris", i: "Endless Space" },
        { n: "Cities Skylines", i: "Tropico 6" },
        { n: "Planet Zoo", i: "Jurassic World Evolution" },
        { n: "RollerCoaster Tycoon", i: "Parkitect" },
        { n: "Little Nightmares", i: "Inside (versão abstrata)" },
        { n: "Ori and the Blind Forest", i: "Child of Light" },
        { n: "Detroit Become Human", i: "Observer" },
        { n: "Until Dawn", i: "Man of Medan" },
        { n: "Stray", i: "Untitled Goose Game" },
        { n: "It Takes Two", i: "Unravel Two" },
        { n: "Tekken", i: "BlazBlue" },
        { n: "Injustice", i: "Power Rangers: Battle for the Grid" },
        { n: "Wii Sports", i: "Ring Fit Adventure" },
        { n: "Asphalt 9", i: "Horizon Chase Turbo" },
        { n: "Temple Run", i: "Jetpack Joyride" },
        { n: "Fruit Ninja", i: "Beat Saber (mobile)" },
        { n: "Persona 5", i: "Tokyo Mirage Sessions" },
        { n: "Yakuza", i: "Mad Max" },
        { n: "Sekiro", i: "Nioh" },
        { n: "Bloodborne", i: "Remnant: From the Ashes" },
        { n: "Monster Hunter", i: "Elden Ring (focado em bosses)" }
    ],

    food: [
        { n: "Cuscuz", i: "Tabule" },
        { n: "Rabada", i: "Estrogonofe de carne" },
        { n: "Esfiha", i: "Chamuça" },
        { n: "Hot dog", i: "Wrap de frango" },
        { n: "Yakult", i: "Kefir" },
        { n: "Fricassê", i: "Curry cremoso" },
        { n: "Pavê", i: "Banoffee" },
        { n: "Coxinha", i: "Bolinho de bacalhau" },
        { n: "Escondidinho", i: "Torta gratinada" },
        { n: "Filé à parmegiana", i: "Carne ao molho madeira" },
        { n: "Torta de frango", i: "Quiche" },
        { n: "Batata frita", i: "Mandioca crocante" },
        { n: "Gelatina", i: "Compota" },
        { n: "Milkshake", i: "Frappuccino" },
        { n: "Donut", i: "Pretzel doce" },
        { n: "Waffle", i: "Rabanada" },
        { n: "Canelone", i: "Gnocchi" },
        { n: "Salsicha empanada", i: "Bolinho crocante" },
        { n: "Isca de peixe", i: "Tiras de lula" },
        { n: "Bacalhau", i: "Polvo grelhado" },
        { n: "Caruru", i: "Moqueca baiana" },
        { n: "Mac and cheese", i: "Sopa cremosa de cheddar" },
        { n: "Ramen", i: "Sopa udon" },
        { n: "Tonkatsu", i: "Carne yakiniku" },
        { n: "Bibimbap", i: "Hot pot" },
        { n: "Shawarma", i: "Fajita" },
        { n: "Chilli", i: "Ensopado mexicano" },
        { n: "Nuggets", i: "Fingers de frango" },
        { n: "Torta holandesa", i: "Torta banoffee" },
        { n: "Pizza doce", i: "Tartelete" },
        { n: "Creme brûlée", i: "Manjar" },
        { n: "Tiramisu", i: "Trifle" },
        { n: "Pêssego em calda", i: "Peras caramelizadas" },
        { n: "Caldo verde", i: "Sopa camponesa" },
        { n: "Moqueca", i: "Ensopado mediterrâneo" },
        { n: "Pizza", i: "Tostada italiana" },
        { n: "Sushi", i: "Temaki invertido" },
        { n: "Feijoada", i: "Goulash" },
        { n: "Churrasco", i: "Chuan (espetinhos chineses)" },
        { n: "Acarajé", i: "Bolinho apimentado africano" },
        { n: "Brigadeiro", i: "Trufa cremosa" },
        { n: "Pastel", i: "Empanada chilena" },
        { n: "Paella", i: "Jambalaya" },
        { n: "Ceviche", i: "Camarão marinado" },
        { n: "Salada Caesar", i: "Salada mediterrânea" },
        { n: "Tacos", i: "Quesadillas" },
        { n: "Pão de queijo", i: "Arepa" },
        { n: "Bolo de cenoura", i: "Bolo de laranja" },
        { n: "Sopa de legumes", i: "Caldo rústico" },
        { n: "Guacamole", i: "Pasta de tahine" },
        { n: "Sorvete", i: "Parfait" },
        { n: "Falafel", i: "Croquete de grão-de-bico" },
        { n: "Omelete", i: "Frittata" },
        { n: "Tapioca", i: "Crepe" },
        { n: "Baião de dois", i: "Feijão tropeiro" },
        { n: "Buchada de bode", i: "Ensopado nordestino" },
        { n: "Galinhada", i: "Arroz à primavera" },
        { n: "Mandioca frita", i: "Milho tostado" },
        { n: "Farofa", i: "Mix de grãos" },
        { n: "Salpicão", i: "Tabule de frango" },
        { n: "Frango xadrez", i: "Gengibre com legumes" },
        { n: "Sakê", i: "Licor de arroz" },
        { n: "Creme de milho", i: "Purê cremoso" },
        { n: "Bolo prestígio", i: "Torta de coco gelada" },
        { n: "Bolo red velvet", i: "Bolo chiffon" },
        { n: "Arroz doce", i: "Arroz cremoso indiano" },
        { n: "Curau", i: "Doce de abóbora cremoso" },
        { n: "Panetone", i: "Rosca doce" },
        { n: "Croissant", i: "Pão folhado rústico" },
        { n: "Fondue", i: "Creme alpino" },
        { n: "Gyoza", i: "Bolinho asiático" },
        { n: "Curry indiano", i: "Ensopado tailandês" },
        { n: "Naan", i: "Pão assado rústico" },
        { n: "Baklava", i: "Rolo folhado doce" },
        { n: "Hummus", i: "Pasta síria" },
        { n: "Nachos", i: "Crackers temperados" },
        { n: "Pipoca doce", i: "Confeito crocante" },
        { n: "Amendoim", i: "Mix de sementes" },
        { n: "Requeijão", i: "Pasta cremosa" },
        { n: "Queijo brie", i: "Queijo de cabra suave" },
        { n: "Gorgonzola", i: "Queijo azul dinamarquês" },
        { n: "Peito de peru", i: "Tiras defumadas" },
        { n: "Mortadela", i: "Linguiça fria" },
        { n: "Carne de sol", i: "Lombo curado" },
        { n: "Bobó de camarão", i: "Ensopado cremoso" },
        { n: "Quibe cru", i: "Mix marinado árabe" },
        { n: "Suco de laranja", i: "Água saborizada" },
        { n: "Toddy", i: "Chocolate quente" },
        { n: "Capuccino", i: "Bebida cremosa" },
        { n: "Café coado", i: "Café filtrado intenso" },
        { n: "Chá-mate", i: "Infusão herbal" },
        { n: "Açaí", i: "Smoothie roxo" },
        { n: "Cocada", i: "Doce caramelizado" },
        { n: "Pé-de-moleque", i: "Croquete doce" },
        { n: "Churros", i: "Rosquinha frita" }
    ],
    places: [
        { n: "Berlim", i: "Zurique" },
        { n: "Amsterdã", i: "Estocolmo" },
        { n: "Moscou", i: "Varsóvia" },
        { n: "Toronto", i: "Boston" },
        { n: "Buenos Aires", i: "Lima" },
        { n: "Honolulu", i: "Fiji" },
        { n: "Serra Gaúcha", i: "Chapada Diamantina" },
        { n: "Fernando de Noronha", i: "Ilha da Madeira" },
        { n: "Acre", i: "Maranhão" },
        { n: "Patagônia", i: "Alasca" },
        { n: "Atenas", i: "Barcelona" },
        { n: "Cidade do Cabo", i: "Maputo" },
        { n: "Viena", i: "Budapeste" },
        { n: "Kyoto", i: "Osaka Antiga (Distrito Histórico)" },
        { n: "Osaka", i: "Kobe" },
        { n: "Hong Kong", i: "Taipei" },
        { n: "Jerusalém", i: "Beirute" },
        { n: "Cancun", i: "Aruba" },
        { n: "Las Vegas", i: "Macau" },
        { n: "Shopping center", i: "Centro de convenções" },
        { n: "Praia deserta", i: "Arquipélago remoto" },
        { n: "Selva tropical", i: "Pantanal" },
        { n: "Groelândia", i: "Sibéria" },
        { n: "Polo Norte", i: "Círculo Ártico" },
        { n: "Gruta/caverna", i: "Cânion estreito" },
        { n: "Parque nacional", i: "Reserva biológica" },
        { n: "Estádio de futebol", i: "Arena multiuso" },
        { n: "Rooftop", i: "Mirante urbano" },
        { n: "Cassino", i: "Bar temático" },
        { n: "Vila medieval", i: "Fortaleza antiga" },
        { n: "Paris", i: "Milão" },
        { n: "Rio de Janeiro", i: "Recife Antigo" },
        { n: "Nova Iorque", i: "Toronto Downtown" },
        { n: "Deserto do Saara", i: "Planície do Kalahari" },
        { n: "Cairo", i: "Doha" },
        { n: "Grand Canyon", i: "Vale da Morte" },
        { n: "Veneza", i: "Santorini" },
        { n: "Sydney", i: "Brisbane" },
        { n: "Machu Picchu", i: "Petra" },
        { n: "Disney (parque)", i: "Parque temático da Lego" },
        { n: "Lisboa", i: "Sevilha" },
        { n: "Praia de Copacabana", i: "Praia do Futuro" },
        { n: "Pequim", i: "Hong Kong" },
        { n: "Dubai", i: "Doha" },
        { n: "Estação espacial", i: "Base subterrânea" },
        { n: "Cataratas do Iguaçu", i: "Seljalandsfoss (Islândia)" },
        { n: "Vaticano", i: "Ilha de Malta" },
        { n: "Zona rural", i: "Distrito interiorano" },
        { n: "Aeroporto", i: "Pátio de embarque marítimo" },
        { n: "Museu", i: "Arquivo histórico" },
        { n: "Camping", i: "Refúgio natural" },
        { n: "Brasília", i: "Niterói" },
        { n: "Curitiba", i: "Blumenau" },
        { n: "Recife", i: "João Pessoa" },
        { n: "João Pessoa", i: "Teresina" },
        { n: "Vitória", i: "Linhares" },
        { n: "Belo Horizonte", i: "Diamantina" },
        { n: "Florianópolis", i: "Itajaí" },
        { n: "Dublin", i: "Cardiff" },
        { n: "Miami", i: "Cancún urbano" },
        { n: "Washington DC", i: "Baltimore" },
        { n: "San Francisco", i: "Seattle" },
        { n: "Cidade do México", i: "Guadalajara" },
        { n: "Bogotá", i: "Cali" },
        { n: "Santiago", i: "La Paz" },
        { n: "Lima", i: "Arequipa" },
        { n: "Havana", i: "Panamá" },
        { n: "Jamaica", i: "Ilhas Cayman" },
        { n: "Noruega", i: "Dinamarca" },
        { n: "Finlândia", i: "Estônia" },
        { n: "Marrocos", i: "Tunísia" },
        { n: "Quênia", i: "Botsuana" },
        { n: "Índia", i: "Bangladesh" },
        { n: "Tailândia", i: "Malásia" },
        { n: "Nova Zelândia", i: "Tasmânia" },
        { n: "Muralha da China", i: "Monte Fuji" },
        { n: "Coliseu", i: "Fórum Romano" },
        { n: "Torre Eiffel", i: "Catedral de Notre-Dame" },
        { n: "Taj Mahal", i: "Templo de Borobudur" },
        { n: "Monte Everest", i: "Monte Elbrus" },
        { n: "Burj Khalifa", i: "Shanghai Tower" },
        { n: "Alpes Suíços", i: "Montanhas do Cáucaso" }
    ],
    objects: [
        { n: "Mouse", i: "Controle de mídia" },
        { n: "Teclado", i: "Tablet gráfico" },
        { n: "Calculadora", i: "Agenda eletrônica" },
        { n: "Pendrive", i: "Cartão SD" },
        { n: "Abajur", i: "Luz LED portátil" },
        { n: "Travesseiro", i: "Protetor de pescoço" },
        { n: "Termômetro", i: "Medidor de pressão" },
        { n: "Pente", i: "Modelador de cabelo" },
        { n: "Pulseira", i: "Anel" },
        { n: "Colar", i: "Broche" },
        { n: "Vaso", i: "Terrário" },
        { n: "Chave inglesa", i: "Torquímetro" },
        { n: "Panela", i: "Caldeirão pequeno" },
        { n: "Estilete", i: "Cortador circular" },
        { n: "Prato", i: "Travessa pequena" },
        { n: "Escada", i: "Andaime pequeno" },
        { n: "Balança", i: "Medidor digital portátil" },
        { n: "Vassoura", i: "Escova de cerdas longas" },
        { n: "Regador", i: "Pulverizador" },
        { n: "Capacete", i: "Protetor auricular" },
        { n: "Binóculo", i: "Monóculo" },
        { n: "Martelo", i: "Formão" },
        { n: "Aspirador portátil", i: "Rodo elétrico" },
        { n: "Ventilador", i: "Purificador de ar" },
        { n: "Perfume", i: "Óleo corporal aromático" },
        { n: "Creme hidratante", i: "Gel calmante" },
        { n: "Toalha", i: "Toalha de mão descartável" },
        { n: "Espelho", i: "Tela reflexiva" },
        { n: "Roteador", i: "Repetidor de sinal" },
        { n: "Tablet", i: "Leitor de anotações digital" },
        { n: "Skate", i: "Hoverboard" },
        { n: "Violão", i: "Ukulele" },
        { n: "Teclado musical", i: "Controlador MIDI" },
        { n: "Tripé", i: "Suporte articulado" },
        { n: "Microfone", i: "Gravador portátil" },
        { n: "Lixeira", i: "Compactador de lixo" },
        { n: "Chave", i: "Fechadura digital" },
        { n: "Guarda-chuva", i: "Sombrinha retrátil" },
        { n: "Óculos", i: "Óculos de proteção" },
        { n: "Mochila", i: "Bolsa tiracolo" },
        { n: "Garrafa", i: "Cantina térmica" },
        { n: "Fone de ouvido", i: "Amplificador de áudio portátil" },
        { n: "Cadeira", i: "Banquinho dobrável" },
        { n: "Lâmpada", i: "Lanterna solar" },
        { n: "Chaleira", i: "Moedor de café" },
        { n: "Livro", i: "Manual ilustrado" },
        { n: "Carregador", i: "Dock de carregamento" },
        { n: "Lanterna", i: "Luz de cabeça" },
        { n: "Escova de dentes", i: "Irrigador dental" },
        { n: "Câmera", i: "Drone com câmera" },
        { n: "Controle remoto", i: "Hub inteligente" },
        { n: "Chuveiro", i: "Aquecedor de ambiente" },
        { n: "Sofá", i: "Chaise" },
        { n: "Fogão", i: "Airfryer" },
        { n: "Cadeado", i: "Fecho magnético" },
        { n: "Extensão elétrica", i: "Estabilizador" },
        { n: "Furadeira", i: "Ferramenta multifuncional" },
        { n: "Nível", i: "Laser de alinhamento" },
        { n: "Serra", i: "Cortador elétrico" },
        { n: "Despertador", i: "Luz despertadora" },
        { n: "Régua", i: "Compasso" },
        { n: "Marcador permanente", i: "Giz líquido" },
        { n: "Estojo", i: "Organizador de bolso" },
        { n: "Lápis", i: "Marcador técnico" },
        { n: "Borracha", i: "Pincel apagável" },
        { n: "Grampeador", i: "Prensa de papel" },
        { n: "Pincel", i: "Espátula de pintura" },
        { n: "Barbante", i: "Cordão encerado" },
        { n: "Fita isolante", i: "Fita térmica" },
        { n: "Isqueiro", i: "Acendedor elétrico" },
        { n: "Cinto", i: "Colete ajustável" },
        { n: "Carteira", i: "Portadocumentos" },
        { n: "Drone", i: "Câmera 360° portátil" },
        { n: "Caixa de som", i: "Amplificador compacto" },
        { n: "Liquidificador", i: "Extrator manual" },
        { n: "Torradeira", i: "Aquecedor de pão" },
        { n: "Tábua de cortar", i: "Base antiderrapante" },
        { n: "Batedeira", i: "Processador manual" },
        { n: "Máquina de lavar", i: "Centrífuga" },
        { n: "Ferro de passar", i: "Escova vaporizadora" },
        { n: "Cortador de unha", i: "Alicate de cutícula" },
        { n: "Mousepad", i: "Suporte ergonômico" },
        { n: "Balde", i: "Contentor flexível" },
        { n: "Edredom", i: "Manta felpuda" },
        { n: "Cortina", i: "Divisória de tecido" },
        { n: "Pia", i: "Tampo de apoio" },
        { n: "Secador", i: "Difusor térmico" },
        { n: "Geladeira", i: "Adega climatizada" },
        { n: "Bicicleta", i: "Scooter elétrica" },
        { n: "Barraca de camping", i: "Rede de descanso" }
    ],

    brands: [
        { n: "KFC", i: "Subway" },
        { n: "Burger King", i: "Outback" },
        { n: "Heineken", i: "Corona" },
        { n: "Red Bull", i: "Gatorade" },
        { n: "Nestlé", i: "Bauducco" },
        { n: "Nivea", i: "Granado" },
        { n: "O Boticário", i: "Avon" },
        { n: "Adidas", i: "Fila" },
        { n: "Lacoste", i: "Tommy Hilfiger" },
        { n: "Under Armour", i: "New Balance" },
        { n: "Converse", i: "Olympikus" },
        { n: "Motorola", i: "BlackBerry" },
        { n: "TCL", i: "AOC" },
        { n: "Fiat", i: "Chevrolet" },
        { n: "Jeep", i: "Škoda" },
        { n: "Renault", i: "Citroën" },
        { n: "Audi", i: "Lexus" },
        { n: "Mercedes-Benz", i: "Infiniti" },
        { n: "Chanel", i: "Givenchy" },
        { n: "Louis Vuitton", i: "Prada" },
        { n: "Ray-Ban", i: "Hawkers" },
        { n: "GoPro", i: "Kodak" },
        { n: "Twitch", i: "Kick" },
        { n: "TikTok", i: "KwAi" },
        { n: "Philips", i: "Mondial" },
        { n: "Razer", i: "Redragon" },
        { n: "HyperX", i: "SteelSeries" },
        { n: "Visa", i: "Elo" },
        { n: "Avon", i: "Mary Kay" },
        { n: "Honda", i: "Suzuki" },
        { n: "Spotify", i: "Amazon Music" },
        { n: "Uber Eats", i: "Rappi" },
        { n: "Shein", i: "C&A" },
        { n: "Vivo", i: "Nextel" },
        { n: "Bradesco", i: "Santander" },
        { n: "Apple", i: "Asus" },
        { n: "Google", i: "Yahoo" },
        { n: "Amazon", i: "eBay" },
        { n: "Ferrari", i: "McLaren" },
        { n: "Toyota", i: "Subaru" },
        { n: "Netflix", i: "Prime Video" },
        { n: "IKEA", i: "Etna" },
        { n: "Pepsi", i: "Guaraná Antarctica" },
        { n: "Starbucks", i: "Café Pilão" },
        { n: "Sony", i: "Sharp" },
        { n: "Intel", i: "Qualcomm" },
        { n: "Dell", i: "Lenovo" },
        { n: "H&M", i: "Forever 21" },
        { n: "Xbox", i: "Nintendo" },
        { n: "Lego", i: "Mega Bloks" },
        { n: "Uber", i: "Cabify" },
        { n: "Steam", i: "GOG" },
        { n: "Blizzard", i: "Bethesda" },
        { n: "Tesla", i: "Lucid Motors" },
        { n: "SpaceX", i: "Blue Origin" },
        { n: "Boeing", i: "Embraer" },
        { n: "FedEx", i: "Correios" },
        { n: "Shopee", i: "Americanas" },
        { n: "Carrefour", i: "Extra" },
        { n: "Casas Bahia", i: "Havan" },
        { n: "Xiaomi", i: "Realme" },
        { n: "JBL", i: "Edifier" },
        { n: "Canon", i: "Fujifilm" },
        { n: "Asus", i: "MSI" },
        { n: "Western Digital", i: "Kingston" },
        { n: "Hot Wheels", i: "Jada Toys" },
        { n: "Fisher-Price", i: "Chicco" },
        { n: "Hasbro", i: "Bandai" },
        { n: "Heinz", i: "Heinz Kraft (variação interna)" },
        { n: "Doritos", i: "Takis" },
        { n: "Fanta", i: "Tampico" },
        { n: "Sprite", i: "7Up" },
        { n: "Omo", i: "Brilhante" },
        { n: "Rexona", i: "Above" },
        { n: "Colgate", i: "Sensodyne" },
        { n: "Riachuelo", i: "Marisa" },
        { n: "Claro", i: "Algar Telecom" },
        { n: "Nubank", i: "C6 Bank" }
    ],
    nature: [
        { n: "Elefante", i: "Rinoceronte-lanoso (extinto)" },
        { n: "Camelo", i: "Boi-almiscarado" },
        { n: "Baleia", i: "Narval" },
        { n: "Serpente", i: "Enguia" },
        { n: "Panda", i: "Lêmure" },
        { n: "Flamingo", i: "Pelicano" },
        { n: "Hiena", i: "Furão" },
        { n: "Morcego", i: "Tarsius" },
        { n: "Caranguejo", i: "Lagosta" },
        { n: "Aranha", i: "Centopeia" },
        { n: "Formigueiro", i: "Toca subterrânea" },
        { n: "Deserto rochoso", i: "Planície árida" },
        { n: "Neblina", i: "Orvalho da manhã" },
        { n: "Chuva forte", i: "Chuva de verão" },
        { n: "Granizo", i: "Chuva congelada" },
        { n: "Maré alta", i: "Corrente marítima" },
        { n: "Lago congelado", i: "Penhasco de gelo" },
        { n: "Orquídea", i: "Flor-de-lótus" },
        { n: "Girassol", i: "Hibisco" },
        { n: "Lírio", i: "Flor-de-cera" },
        { n: "Musgo", i: "Folhagem úmida" },
        { n: "Céu estrelado", i: "Nebulosa distante" },
        { n: "Eclipse lunar", i: "Alinhamento planetário" },
        { n: "Fóssil", i: "Formação rochosa antiga" },
        { n: "Corais", i: "Recife fossilizado" },
        { n: "Raposa", i: "Dhole" },
        { n: "Búfalo", i: "Iamau (boi-do-himalaia)" },
        { n: "Salamandra", i: "Axolote" },
        { n: "Tartaruga", i: "Tartaruga-de-couro" },
        { n: "Onça-pintada", i: "Caracal" },
        { n: "Tucano", i: "Calau" },
        { n: "Gavião", i: "Falcão-peregrino" },
        { n: "Leão", i: "Chita" },
        { n: "Golfinho", i: "Marlin" },
        { n: "Vulcão", i: "Gêiser" },
        { n: "Cacto", i: "Planta desértica espinhosa" },
        { n: "Borboleta", i: "Inseto-pavão" },
        { n: "Coruja", i: "Kea (papagaio-da-nova-zelândia)" },
        { n: "Cachoeira", i: "Nascente cristalina" },
        { n: "Tufão (furacão)", i: "Ciclone tropical" },
        { n: "Iceberg", i: "Campo de gelo" },
        { n: "Pinguim", i: "Albatroz" },
        { n: "Aurora boreal", i: "Cintilação atmosférica" },
        { n: "Manguezal", i: "Costa lamacenta" },
        { n: "Gorila", i: "Bonobo" },
        { n: "Rinoceronte", i: "Boi-selvagem" },
        { n: "Antílope", i: "Oryx" },
        { n: "Bicho-preguiça", i: "Tamanduá" },
        { n: "Ornitorrinco", i: "Musaranho" },
        { n: "Guepardo", i: "Serval" },
        { n: "Jacaré", i: "Lagarto-monitor" },
        { n: "Medusa do mar", i: "Plâncton bioluminescente" },
        { n: "Cavalo-marinho", i: "Peixe-mandarim" },
        { n: "Lula", i: "Náutilo" },
        { n: "Estrela-do-mar", i: "Esponja-marinha" },
        { n: "Cogumelo", i: "Trufa" },
        { n: "Esquilo", i: "Pika (roedor do Himalaia)" },
        { n: "Coelho", i: "Pika europeu" },
        { n: "Rena", i: "Cabra-da-montanha" },
        { n: "Morsa", i: "Leão-marinho" },
        { n: "Pavão", i: "Faisão-dourado" },
        { n: "Cisne", i: "Mergulhão" },
        { n: "Capivara", i: "Aguti" },
        { n: "Sapo", i: "Rã-arborícola" },
        { n: "Cobra coral", i: "Serpente-de-leite" },
        { n: "Besouro", i: "Gorgulho" },
        { n: "Libélula", i: "Mosca-de-água" },
        { n: "Arco-íris", i: "Halo solar" },
        { n: "Meteoro", i: "Rastro de satélite" },
        { n: "Cristal", i: "Mineral lapidado" },
        { n: "Ametista", i: "Granada" }
    ],
    professions: [
        { n: "Bibliotecário", i: "Arquivista" },
        { n: "Biólogo", i: "Pesquisador de Campo" },
        { n: "Químico", i: "Analista Laboratorial" },
        { n: "Garçom", i: "Host de Restaurante" },
        { n: "Porteiro", i: "Atendente de Recepção" },
        { n: "Pedreiro", i: "Técnico em Construção" },
        { n: "Eletricista", i: "Instalador de Sistemas" },
        { n: "Marceneiro", i: "Restaurador de Móveis" },
        { n: "Técnico de TI", i: "Analista de Suporte" },
        { n: "Fotógrafo", i: "Editor de Imagens" },
        { n: "Youtuber", i: "Criador de Conteúdo Digital" },
        { n: "Influenciador digital", i: "Consultor de Imagem" },
        { n: "Podcaster", i: "Entrevistador" },
        { n: "Dançarino", i: "Performista" },
        { n: "DJ", i: "Curador Musical" },
        { n: "Corretor de imóveis", i: "Consultor de Investimentos" },
        { n: "Analista de dados", i: "Especialista em BI" },
        { n: "Contador", i: "Auditor" },
        { n: "Mecânico", i: "Operador de Manutenção" },
        { n: "Pintor", i: "Designer de Cenários" },
        { n: "Bancário", i: "Consultor Financeiro" },
        { n: "Publicitário", i: "Especialista em Marketing" },
        { n: "Terapeuta ocupacional", i: "Educador Físico" },
        { n: "Metalúrgico", i: "Operador Industrial" },
        { n: "Piloto de helicóptero", i: "Instrutor de Voo" },
        { n: "Estagiário", i: "Auxiliar Administrativo" },
        { n: "Guia turístico", i: "Agente de Viagens" },
        { n: "Matemático", i: "Pesquisador Acadêmico" },
        { n: "Astrônomo", i: "Analista Espacial" },
        { n: "Atleta", i: "Preparador Físico" },
        { n: "Personal organizer", i: "Consultor de Rotina" },
        { n: "Maquiador", i: "Consultor de Beleza" },
        { n: "Pescador", i: "Vendedor de Pescados" },
        { n: "Jardineiro", i: "Cuidador de Estufas" },
        { n: "Sapateiro", i: "Designer de Calçados" },
        { n: "Médico", i: "Pesquisador Clínico" },
        { n: "Professor", i: "Instrutor Particular" },
        { n: "Bombeiro", i: "Socorrista" },
        { n: "Advogado", i: "Consultor Jurídico" },
        { n: "Jornalista", i: "Redator" },
        { n: "Cozinheiro", i: "Gastrônomo" },
        { n: "Motorista", i: "Condutor Particular" },
        { n: "Dentista", i: "Especialista em Saúde Bucal" },
        { n: "Policial", i: "Agente de Operações" },
        { n: "Cientista", i: "Pesquisador Independente" },
        { n: "Agricultor", i: "Supervisor Rural" },
        { n: "Psicólogo", i: "Conselheiro" },
        { n: "Veterinário", i: "Cuidador Animal" },
        { n: "Ator/atriz", i: "Apresentador" },
        { n: "Barbeiro", i: "Especialista em Estilo Masculino" },
        { n: "Recepcionista", i: "Atendente Corporativo" },
        { n: "Tradutor", i: "Revisor Multilíngue" },
        { n: "Engenheiro Civil", i: "Planejador de Obras" },
        { n: "Engenheiro de Software", i: "Administrador de Sistemas" },
        { n: "Arqueólogo", i: "Pesquisador Cultural" },
        { n: "Historiador", i: "Curador" },
        { n: "Geógrafo", i: "Analista Ambiental" },
        { n: "Meteorologista", i: "Pesquisador Climático" },
        { n: "Oceanógrafo", i: "Analista Marinho" },
        { n: "Nutricionista", i: "Especialista em Alimentação" },
        { n: "Coach", i: "Mentor" },
        { n: "Analista de QA", i: "Analista de Processos" },
        { n: "Designer UX", i: "Consultor de Experiência" },
        { n: "Revisor textual", i: "Curador de Conteúdo" },
        { n: "Roteirista", i: "Criador de Narrativas" },
        { n: "Ilustrador", i: "Artista Visual" },
        { n: "Animador 3D", i: "Designer de Movimentação" },
        { n: "Cenógrafo", i: "Planejador de Ambientação" },
        { n: "Treinador de animais", i: "Comportamentalista Animal" },
        { n: "Técnico agrícola", i: "Consultor Agropecuário" },
        { n: "Soldador", i: "Montador Industrial" },
        { n: "Operador de caixa", i: "Atendente de Loja" },
        { n: "Almoxarife", i: "Controlador de Estoque" },
        { n: "Supervisor", i: "Coordenador" },
        { n: "Cientista de dados", i: "Analista de Machine Learning" },
        { n: "Pediatra", i: "Médico Geral" },
        { n: "Ginecologista", i: "Especialista Clínico" },
        { n: "Dermatologista", i: "Consultor Estético" },
        { n: "Cardiologista", i: "Especialista Hospitalar" },
        { n: "Motoboy", i: "Mensageiro" },
        { n: "Caminhoneiro", i: "Transportador" },
        { n: "Maquinista", i: "Condutor Ferroviário" },
        { n: "Comissário de bordo", i: "Atendente de Voo" },
        { n: "Capitão de navio", i: "Navegador" },
        { n: "Guarda florestal", i: "Fiscal Ambiental" },
        { n: "Sommelier", i: "Consultor de Vinhos" },
        { n: "Confeiteiro", i: "Criador de Doces" },
        { n: "Chocolatier", i: "Especialista em Cacau" },
        { n: "Fiscal de obras", i: "Consultor de Infraestrutura" },
        { n: "Promotor", i: "Analista Jurídico" },
        { n: "Investigador", i: "Analista Forense" },
        { n: "Vigilante", i: "Monitor de Segurança" },
        { n: "Cantor lírico", i: "Intérprete Vocal" },
        { n: "Maestro", i: "Diretor Musical" },
        { n: "Modelista", i: "Criador de Moldes" },
        { n: "Designer de joias", i: "Artista de Metal" }
    ],
    questions: [
        { n: "O que você mais gosta de fazer no domingo?", i: "Qual é o seu ritual perfeito para começar a semana?" },
        { n: "Qual foi o último filme que você viu?", i: "Qual tipo de filme você evita assistir?" },
        { n: "O que você nunca colocaria no seu quarto?", i: "Qual objeto estranho você já viu no quarto de alguém?" },
        { n: "Qual é sua comida de conforto?", i: "Qual prato você só come em ocasiões especiais?" },
        { n: "Se pudesse voltar no tempo, onde iria?", i: "Qual momento histórico você gostaria de testemunhar?" },
        { n: "Uma coisa que você compra todo mês?", i: "Qual compra você vive adiando?" },
        { n: "O que você sempre perde em casa?", i: "Qual objeto você sempre deixa no mesmo lugar?" },
        { n: "Um lugar que você quer fugir agora?", i: "Qual lugar te traz sensação imediata de segurança?" },
        { n: "Algo que você não viveria sem?", i: "O que você aprendeu a viver sem?" },
        { n: "Que animal você adotaria?", i: "Qual animal você acha mais interessante na natureza?" },
        { n: "Como você descreve seu estilo musical?", i: "Qual música te marcou na infância?" },
        { n: "Qual bebida combina com você?", i: "Qual bebida você sempre vê alguém pedindo mas nunca experimentou?" },
        { n: "Seu passatempo secreto?", i: "Uma atividade que você gostaria de aprender um dia?" },
        { n: "Qual clima combina contigo?", i: "Em qual clima você sente mais dificuldade de se concentrar?" },
        { n: "O que te distrai fácil?", i: "O que te ajuda a manter a atenção?" },
        { n: "Qual superpoder você teria?", i: "Qual herói você acha superestimado?" },
        { n: "Uma coisa que você compra só por impulso?", i: "Qual item você pesquisa muito antes de comprar?" },
        { n: "Onde você gostaria de trabalhar?", i: "Qual ambiente de trabalho você acha mais inspirador?" },
        { n: "Um objeto que representa você?", i: "Qual objeto você considera inútil mas divertido?" },
        { n: "Como é seu café da manhã ideal?", i: "Qual refeição do dia você costuma pular?" },
        { n: "Onde você iria num encontro perfeito?", i: "Qual lugar combina com um encontro simples e rápido?" },
        { n: "Uma mania que você tem?", i: "Qual hábito você gostaria de desenvolver?" },
        { n: "Qual cheiro te traz memórias?", i: "Qual cheiro você associa com viagens?" },
        { n: "O que você faria se ficasse invisível?", i: "O que você faria se tivesse supervelocidade?" },
        { n: "Uma viagem que você repetiria?", i: "Um destino que você tem curiosidade mas nunca foi?" },
        { n: "Um instrumento que gostaria de tocar?", i: "Qual artista te inspira musicalmente?" },
        { n: "O que te deixa feliz instantaneamente?", i: "O que você faz para melhorar o dia de outra pessoa?" },
        { n: "Se fosse comida, qual seria?", i: "Se fosse uma cor, qual você seria?" },
        { n: "Se fosse um lugar, qual seria?", i: "Que cidade você acha bonita mesmo sem vontade de morar?" },
        { n: "O que te tira do sério rápido?", i: "O que você considera um bom descanso?" },
        { n: "Qual esporte você assistiria?", i: "Qual esporte você acha bonito mesmo sem acompanhar?" },
        { n: "O que nunca falta na sua mochila?", i: "Qual objeto você só usa em emergências?" },
        { n: "Como você descreveria seu humor hoje?", i: "O que costuma melhorar seu humor?" },
        { n: "Qual personagem você seria?", i: "Qual universo fictício você gostaria de visitar?" },
        { n: "O que você colecionaria?", i: "O que você adoraria ganhar repetido?" },
        { n: "Se pudesse teleportar, para onde iria?", i: "Qual lugar parece mais interessante visto em fotos?" },
        { n: "O que você faria com 24h sem regras?", i: "O que faria se tivesse 24h completamente planejadas?" },
        { n: "Qual seria seu filme favorito?", i: "Qual gênero de filme você só assiste quando está no clima certo?" },
        { n: "Como você descreveria sua profissão?", i: "Que profissão você admira mesmo sem querer ter?" },
        { n: "Qual comida você escolheria para o fim do mundo?", i: "Que comida você comeria apenas uma vez na vida?" },
        { n: "Qual cidade você quer visitar primeiro?", i: "Uma cidade que você só conheceria em uma viagem longa?" },
        { n: "Que objeto você sempre carrega?", i: "Qual objeto você já tentou abandonar e não conseguiu?" },
        { n: "Como você chama um grupo de amigos?", i: "Como você descreve um grupo muito bagunçado?" },
        { n: "O que te deixa nervoso?", i: "O que te faz respirar fundo antes de agir?" },
        { n: "Onde você passaria as férias?", i: "Qual destino combina com uma viagem rápida de última hora?" },
        { n: "Qual é seu transporte diário?", i: "Qual transporte você usaria só em situações especiais?" },
        { n: "O que você pede num restaurante?", i: "O que você raramente pede mas gosta muito?" },
        { n: "Qual aparelho você usa mais em casa?", i: "Qual aparelho você evita usar?" },
        { n: "Como é seu quarto ideal?", i: "Qual parte da casa você mudaria primeiro?" },
        { n: "Em qual época do ano você nasce?", i: "Qual época do ano te inspira mais?" },
        { n: "O que você faria com um milhão?", i: "O que você faria se ganhasse um presente inesperado?" },
        { n: "Prefere praia ou montanha?", i: "Qual tipo de paisagem você gosta de fotografar?" },
        { n: "Como você acorda pela manhã?", i: "Qual é o seu maior inimigo quando tenta dormir?" },
        { n: "Qual aplicativo você usa sempre?", i: "Qual app você só abre quando lembra?" },
        { n: "Qual presente você daria?", i: "Qual presente você considera universal para qualquer pessoa?" },
        { n: "O que faria num fim de semana livre?", i: "Qual atividade você evita quando está cansado?" },
        { n: "Qual profissão você quis ter quando criança?", i: "Qual profissão você descobriu depois de adulto?" },
        { n: "Como é seu estilo de roupa?", i: "Qual peça você gosta mas quase nunca usa?" },
        { n: "O que te relaxa depois do trabalho?", i: "O que você faz quando precisa recarregar energia rápido?" },
        { n: "Como você descreve uma festa perfeita?", i: "O que você considera essencial para um evento simples?" },
        { n: "Quantas horas você dorme?", i: "Qual horário você considera impossível acordar?" },
        { n: "Qual é sua bebida favorita?", i: "Qual bebida te surpreendeu quando provou pela primeira vez?" },
        { n: "Qual viagem marcou sua vida?", i: "Qual lugar você sonhava conhecer quando era criança?" },
        { n: "Qual música sempre te deixa animado?", i: "Que tipo de som você coloca quando quer relaxar?" },
        { n: "Qual esporte você mais gosta de praticar?", i: "Se pudesse aprender uma habilidade física nova, qual seria?" },
        { n: "Qual foi o melhor presente que já recebeu?", i: "Qual presente você adoraria dar para alguém importante?" },
        { n: "Qual é o seu tipo de comida preferido?", i: "O que você costuma comer quando está com pressa?" },
        { n: "O que você mais gosta de fazer nas férias?", i: "Qual foi sua pior experiência viajando?" },
        { n: "Qual foi o último filme que você assistiu?", i: "Que filme você vive enrolando para ver?" },
        { n: "O que mais te deixa com vergonha?", i: "O que quase nada te afeta ou te deixa desconfortável?" },
        { n: "Qual é o seu hobby preferido?", i: "Que atividade você queria tentar, mas nunca começou?" },
        { n: "O que você faria se ganhasse um milhão?", i: "Qual foi o maior gasto por impulso que já fez?" },
        { n: "Qual animal você adotaria?", i: "Se você fosse um animal por um dia, qual seria?" },
        { n: "O que sempre te faz rir?", i: "O que raramente você acha engraçado?" },
        { n: "Qual é a sua sobremesa favorita?", i: "O que você costuma comer quando quer algo simples?" },
        { n: "O que você mais valoriza em uma amizade?", i: "Qual comportamento te faz se afastar de alguém?" },
        { n: "Qual livro te marcou?", i: "Que tipo de história você não consegue terminar?" },
        { n: "Qual lugar você gosta de revisar suas ideias?", i: "Onde você costuma passar tempo quando não quer pensar em nada?" },
        { n: "Qual série você mais maratonou?", i: "Qual série você começou e não terminou?" },
        { n: "Qual cheiro te traz boas lembranças?", i: "Qual cheiro você raramente percebe no dia a dia?" },
        { n: "O que você gosta de cozinhar?", i: "Se pudesse pedir uma comida agora, qual seria?" },
        { n: "Qual jogo você mais jogou na vida?", i: "Que tipo de jogo você jogaria só para passar o tempo?" },
        { n: "Qual foi o melhor show que já viu?", i: "Que artista você só ouviu depois de muita insistência?" },
        { n: "O que mais te motiva?", i: "O que faz você perder o foco às vezes?" },
        { n: "Qual é sua bebida favorita?", i: "O que você costuma beber quando não tem opções?" },
        { n: "Qual hábito seu você mais gosta?", i: "Que hábito você tenta mudar, mas ainda não conseguiu?" },
        { n: "O que você mais gosta em festas?", i: "O que mais te incomoda em encontros sociais?" },
        { n: "Qual roupa você mais usa?", i: "Qual peça você comprou e quase nunca usa?" },
        { n: "O que te ajuda a acordar melhor?", i: "O que faz você dormir mal às vezes?" },
        { n: "Qual é seu estilo musical favorito?", i: "Que estilo você só escuta em momentos específicos?" },
        { n: "O que você sempre leva na mochila?", i: "O que você sempre esquece em casa?" },
        { n: "Qual aplicativo você mais usa?", i: "Qual app você instalou e nunca mais abriu?" },
        { n: "Qual foi seu aniversário mais legal?", i: "Qual data você quase sempre esquece?" },
        { n: "O que você gosta de aprender?", i: "O que você acha difícil de memorizar?" },
        { n: "Qual esporte você gosta de assistir?", i: "Que tipo de competição você raramente acompanha?" },
        { n: "Qual cheiro te lembra infância?", i: "Que cheiro você só encontra em lugares específicos?" },
        { n: "O que você faria num dia de folga?", i: "Como você passa tempo quando está sem energia?" },
        { n: "O que você mais gosta de organizar?", i: "O que mais bagunça sua rotina?" },
        { n: "Qual app você não vive sem?", i: "Qual tecnologia você acha complicadíssima?" },
        { n: "Qual foi o último sonho que lembra?", i: "Que tipo de sonho você quase nunca tem?" },
        { n: "Qual comida você nunca enjoa?", i: "Qual comida você só come em ocasiões especiais?" },
        { n: "O que te deixa empolgado instantaneamente?", i: "O que quase nunca muda seu humor?" },
        { n: "Qual é sua estação favorita do ano?", i: "Qual clima mais te deixa indeciso?" },
        { n: "Qual hábito suas manhãs têm?", i: "Qual coisa você só faz quando sobra tempo?" },
        { n: "O que você ama do seu bairro?", i: "O que você quase não usa na sua cidade?" },
        { n: "Qual filme você sabe falas de cabeça?", i: "Que filme você assistiu e mal lembra?" },
        { n: "O que você sempre pede no delivery?", i: "O que você só come quando está na rua?" },
        { n: "Que tipo de vídeo você gosta de assistir?", i: "Que tipo de vídeo você raramente clica?" },
        { n: "O que você gosta de colecionar?", i: "O que você vive perdendo?" },
        { n: "O que te acalma rápido?", i: "O que te irrita só um pouco, mas não muito?" },
        { n: "Qual foi a última novidade que você aprendeu?", i: "Que assunto você ainda quer entender melhor?" },
        { n: "Onde você gosta de sentar em restaurantes?", i: "Onde você acaba sentando quando não tem opção?" },
        { n: "O que você gosta de fazer quando está sozinho?", i: "O que você evita fazer com muita gente por perto?" },
        { n: "Qual protesto você já participou?", i: "Qual causa você só acompanhou pela internet?" },
        { n: "O que você já quebrou sem querer?", i: "Que objeto você protege demais para não quebrar?" },
        { n: "Qual mania sua é engraçada?", i: "Qual mania você só percebeu depois que comentaram?" },
    ]
};